### ISSUE TITLE
Error when make the skid

### ISSUE THREAD

**Issue by wuchenglon** [N-BodyShop/skid#1]
I am installing skid from N-body shop by file README and when I make the code it returned an error as follows:
cc -O3   -c -o main.o main.c
main.c: In function ‘main’:
main.c:75:9: warning: implicit declaration of function ‘feenableexcept’; did you mean ‘feraiseexcept’? [-Wimplicit-function-declaration]
   75 |         feenableexcept(FE_OVERFLOW | FE_DIVBYZERO | FE_INVALID);
      |         ^~~~~~~~~~~~~~
      |         feraiseexcept
main.c:104:20: error: ‘HUGE’ undeclared (first use in this function)
  104 |         fTempMax = HUGE;
      |                    ^~~~
main.c:104:20: note: each undeclared identifier is reported only once for each function it appears in

I use VMware 16 workstation with ubuntu-22.04.1-desktop-amd64 ,gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)

**Comment by trquinn** [comment]
Fixed in commit a5d0f330f6676ce045b715fad619e553e256feff
